### PR TITLE
Add Read instances

### PR DESCRIPTION
**Pull request by dzhus**
I wanted to read a `Filter` and it kinda escalated…

### CODE REVIEW

**Comment by bitemyapp** [comment]
I really loathe read for being partial, but I'll give in on this if @MichaelXavier gives it :+1:

**Comment by MichaelXavier** [comment]
@bitemyapp there's definitely ways to use read in a way that produces a Maybe. Personally I only use it for code that isn't performance sensitive at all like CLI flags since show/read are slow and space inefficient, but I wouldn't be prescriptive about that.

I do see a bug here though that should probably be fixed: BH uses a custom `Show` instance for `TimeInterval` which as far as I can tell is only used to implement `ToJSON Interval`. There's an implication that `Show` and `Read` should round-trip, so `Show TimeInterval` should be instead derived and the `show interval` in `ToJSON Interval` should just be inlined in a where clause or something. tl;dr: derived `Read` should only be used in the presence of derived `Show`.

**Comment by dzhus** [comment]
I'll take a look thanks for the comment

**Comment by bitemyapp** [comment]
@MichaelXavier >there's definitely ways to use read in a way that produces a Maybe.

I know, but people don't. Sounds like you're alright with it as long as the bug is fixed, so so am I.

**Comment by dzhus** [comment]
Hey guys, I've fixed the instance for `TimeInterval`, please take a look again

**Comment by bitemyapp** [comment]
@dzhus works for me, thank you :)

**Pull request merged**
