### PR TITLE
Bump dependencies to support GHC 8.2

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
This should be of interest: https://ghc.haskell.org/trac/ghc/ticket/13744

**Comment by 23Skidoo** [comment]
@bitemyapp Ping.

**Comment by MichaelXavier** [comment]
This looks pretty uncontroversial to me.

**Comment by bitemyapp** [comment]
@MichaelXavier good enough for me.

**Comment by 23Skidoo** [comment]
Thanks!

**Comment by zeha** [comment]
Hey, could you consider making a release with this fix? Thanks a bunch!

**Pull request merged**
