### PR TITLE
Comment out comments in the example properly.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by bitemyapp** [comment]
@23Skidoo what sad turn of fate has you looking at an Elasticsearch client?

**Comment by 23Skidoo** [comment]
@bitemyapp We're using it at $JOB.

**Comment by bitemyapp** [comment]
@23Skidoo my condolences

**Comment by 23Skidoo** [comment]
@bitemyapp It's only for logging, so I hope to preserve my sanity.

**Comment by bitemyapp** [comment]
@23Skidoo That should be okay actually! I'd still broadcast the logs onto the local disk and maybe somewhere else if they're important (Could vary this behavior by severity)

YMMV.

https://github.com/Soostone/katip has some ways of doing this if you haven't seen it.

**Comment by 23Skidoo** [comment]
@bitemyapp Thanks!

**Pull request merged**
