### PR TITLE
url query encoding bug

### PR DESCRIPTION
**Pull request by bermanjosh**
@bitemyapp Sorry, I missed a small bug based on the different way the query parameter renderer worked

### CODE REVIEW

**Comment by bitemyapp** [comment]
@bermanjosh thank you for catching this, but could you write a test that exercises the bug you're fixing please? I don't want a regression to occur.

**Comment by bermanjosh** [comment]
@bitemyapp I'm sorry, but I have no idea why CI is failing. The log says it's tripping `hspec-1.12.4`. I thought that's excluded in the cabal file.

**Comment by bitemyapp** [comment]
@bermanjosh probably TravisCI is fucking us. Now we do the dance of death where I swat the .travis.yml and bounce your build until it works. Sorry mate, I'll ping you if I run into a non-spurious error. :|

**Comment by bitemyapp** [comment]
@bermanjosh I'm just going to merge it and see what happens.

**Comment by bermanjosh** [comment]
@bitemyapp Good to know I'm not going crazy - let me know if I missed something (again...).

**Comment by bitemyapp** [comment]
@bermanjosh https://travis-ci.org/bitemyapp/bloodhound/builds/76873638

Nope, you're in good shape. The builds use Stack instead of cabal-install now.

**Pull request merged**
