### PR TITLE
Sorted version of getInitialScroll for V5 client

### PR DESCRIPTION
**Pull request by WraithM**
Elasticsearch 2/5 seems to be able to do sorted scrolling searches. I wanted to make a sorted scroller, and this worked well for me.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Are there any other variations of the scroll API we may support? This may be calling for a more configurable API.

**Comment by WraithM** [comment]
Great question. At least for me, I haven't needed anything other than the sorting.

**Comment by WraithM** [comment]
We could also merge my version of `getInitialScroll` with the original. We could put some flag on it to force sort by `_doc` or not.

**Comment by WraithM** [comment]
Any thoughts on this? There don't seem to be any other unimplemented aspects of the scroll api. It just has that note about using _doc sort for optimizations.

https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-request-scroll.html

**Comment by MichaelXavier** [comment]
@bitemyapp what do you think? Sounds like as it stands there are 2 variations of the scroll API that are as separate functions in the code. We could unify them and break API or keep the 2 functions, wait and see if more are added in future ES versions and then maybe do a unification and break then? I'm leaning towards the latter.

**Comment by bitemyapp** [comment]
@MichaelXavier I prefer the latter meself.

**Pull request merged**
