### PR TITLE
Date range agg

### PR DESCRIPTION
**Pull request by MichaelXavier**
Excuse the giant diff here, I may be bad at PRs. I based my PR off of the as-yet-unmerged low-level-scroll PR, so the diff should shrink significantly after that merge.

This adds the date range aggregation type feature.

### CODE REVIEW

**Comment by bitemyapp** [comment]
@MichaelXavier does this pull in index aliases stuff as well?

**Comment by MichaelXavier** [comment]
Ah looks like it does. I'll go ahead and get that PR fixed. Then the merge order should be index aliases -> low level scroll -> date range agg.

**Comment by bitemyapp** [comment]
@MichaelXavier I'd be fine merging one big mother PR into master. Saves me bookkeeping :P

**Comment by MichaelXavier** [comment]
Fair enough. Since its already in here I'll just use this branch as a start point. AFAICT the only things I need to do are loosen up the "errors" package in test to get tests running again and then add some integration tests for index settings update. @bitemyapp any reason not to just merge those to master? I think the trip up with the huge diff was that I forgot that my index-aliases branch didn't go to master but this PR is targeting master.

**Comment by bitemyapp** [comment]
@MichaelXavier merged index-aliases followed by low-level scroll, I think. Let me know if you need me to do anything else! Thank you as always :bear:

**Comment by bitemyapp** [comment]
@MichaelXavier https://travis-ci.org/bitemyapp/bloodhound/jobs/91447777#L684 ??? Weird.

**Comment by MichaelXavier** [comment]
@bitemyapp this happens when it can't parse the response even though it was successful. I suspect there was a change to the response format in that version of ES. Not sure how I'm going to check that yet...

**Comment by MichaelXavier** [comment]
We've got a green test suite! Merge at will.

There was 1 semantic change but I think its for the better. The issue was that specifically 1.4.1 returned a different alias format than any other version, including 1.4.5. This was easily accounted for. I couldn't figure this out from the "impossible" exception case of bloodhound raising a status code exception on a 200. You'd have to be pretty clued into the library design to know that this means it couldn't parse the body as the expected type nor as an error. I figure that this case represents an error at the protocol level and there's nothing that bloodhound can do but throw. The alternative of a cascading Either (multiple eithers) was not attractive. When something like this comes up, its either a bug in bloodhound or its a version that is not supported. Now, this hopefully rare codepath throws a custom `EsProtocolException` that includes the response body that it barfed on. In the surrounding docs the user is encouraged to submit this as a bug on the issue tracker.

If all of this sounds good, go ahead and merge and we can close #78 and #76.

**Comment by bitemyapp** [comment]
@MichaelXavier Damn!  :alarm_clock: alarm_clock: alarm_clock: :fire:

Thank you as always! Between this and the Stackage pings, I'll be looking to push out a release soon.

**Pull request merged**
