### PR TITLE
Add travis output to prevent stalling

### PR DESCRIPTION
**Pull request by MichaelXavier**
This is for #194

### CODE REVIEW

**Comment by bitemyapp** [comment]
@MichaelXavier I think `travis_wait` works for the 10 minute output case? Does the busy-spinner do something TravisCI's provided thingy would not?

https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

This PR build failed because we hit the 50 minute global limit on a couple of the jobs.

[You won't like the answer](https://github.com/travis-ci/travis-ci/issues/2736#issuecomment-109778499)

**Comment by bitemyapp** [comment]
For an idea of the speed-gap between dedis and AWS-based CI services like CircleCI and TravisCI: http://bitemyapp.com/posts/2016-03-28-speeding-up-builds.html

**Comment by bitemyapp** [comment]
I am giving this a crack right now.

**Comment by bitemyapp** [comment]
https://github.com/travis-ci/travis-ci/issues/7020 christ on sale

**Comment by bitemyapp** [comment]
screen shot 2017-07-13 at 1 36 31 am
screen shot 2017-07-13 at 2 06 27 am

should be g2g now, merge if you're happy. imma pass tf out now

**Comment by MichaelXavier** [comment]
LOL. I wasn't aware of travis_wait. That's just like me for a system to report an error with a page to read more and for me to not visit that page and come up with some much dumber solution. This seems like a better solution, thanks!

**Comment by bitemyapp** [comment]
@MichaelXavier FWIW, there's a trade-off here. I halved our build time but our cache payloads are _huge_ (~6gb per PR/branch) now, but without having done so, our builds wouldn't have been passing anyway. That means cache upload period at end of build is longer. I think it's worth it, but keep it in mind in case we have problems later.

The other thing I did to speed up our builds was turn on `--fast` for build and test.

**Comment by MichaelXavier** [comment]
Good point. Yeah since we're not building any artifacts with our CI, may as well use --fast to speed things up slightly.

**Pull request merged**
