### PR TITLE
Support GHC 8.8 for 0.16.0.0

### PR DESCRIPTION
**Pull request by soareschen**
While waiting for the next major release of Bloodhound, we'd like to use the current released version (0.16.0.0) with GHC 8.8 and 8.10 support. I'd appreciate if you can do a minor release 0.16.0.1 to make life easier for current users.

---
This change is [Reviewable](https://reviewable.io/reviews/bitemyapp/bloodhound/269)

### CODE REVIEW

**Comment by arybczak** [comment]
There are multiple conflicts.

**Comment by soareschen** [comment]
The conflicts are because the PR is configured to merge against master, while it should have merge with the `0.16.0.0` tag. But I can't create a PR for a git tag, and there is no branch corresponding to 0.16.0.0.

**Comment by arybczak** [comment]
Can we please get this PR merged against 4c743e1082b8b5eec53a7155733999441be0efce (0.16.0.0) and released as 0.16.0.1 so that downstream packages work with GHC 8.8 and 8.10? It's 5 minutes of work. @bitemyapp @MichaelXavier

**Comment by wraithm** [comment]
@bitemyapp @MichaelXavier 

Ping

**Comment by bitemyapp** [comment]
@arybczak @wraithm 
Screen Shot 2020-07-27 at 8 54 19 PM

Fix the merge conflicts and I'll review with an intent to merge if there aren't issues. Looks sundry to me.

**Comment by wraithm** [comment]
@bitemyapp The problem is that this should be merged into 0.16.0.0, as OP mentioned. I don't think it makes sense to merge this into master. Is there some way to make a pull request target that specific commit without a tag or an existing branch? What are your thoughts?

**Comment by bitemyapp** [comment]
@wraithm I'm not entirely sure what you are asking for. Could you please explain in more explicit terms what it is you want me to do?

**Comment by wraithm** [comment]
I'd like you to create a branch at hash `4c743e1082b8b5eec53a7155733999441be0efce` for this PR to target. The branch should probably be called `0.16` or something like that. This PR should then be merged into that branch and released onto hackage as 0.16.1.0 or something like that.

This PR should target 0.16, not 0.17, and therefore should be merged into or based on the last 0.16 commit. However, we cannot make the branch for you. You need to do that.

**Comment by bitemyapp** [comment]
I cut releases from `master`. I won't make an exception here. Sorry!

**Comment by jonathanjouty** [comment]
@bitemyapp what can we do to get GHC 8.8 support before the next major version of `bloodhound` is out?

**Comment by wraithm** [comment]
@bitemyapp I'm happy to do the maintenance work here.

**Comment by bitemyapp** [comment]
Screen Shot 2020-07-30 at 9 39 49 PM
Screen Shot 2020-07-30 at 9 39 45 PM

@wraithm 君の番だよ

**Comment by wraithm** [comment]
ありがとうございました、Ｃｈｒｉｓさん。

いつでも君の君になります。私が日本語を話すのをどうやって知っていますか？

**Pull request merged**
