### PR TITLE
add stats aggregation

### PR DESCRIPTION
**Pull request by shmish111**

### CODE REVIEW

**Comment by shmish111** [comment]
Looks like Travis timed out one of the builds, all others passed all tests etc so I'm pretty sure it's fine

**Comment by MichaelXavier** [comment]
I've restarted that build. Seems like the larger your built matrix the more likely you'll end up getting a rotten Travis run.

**Comment by shmish111** [comment]
OK, build passing, FYI I am currently using this in prod, working well, I just want to get rid of the bloodhound fork in my app asap :)

**Comment by MichaelXavier** [comment]
LGTM :+1: , @bitemyapp ?

**Comment by bitemyapp** [comment]
Has a test, looks pretty compact. I'll merge.

**Comment by shmish111** [comment]
Thanks guys, @bitemyapp when will the next version be released to hackage?

**Comment by bitemyapp** [comment]
@shmish111 when either myself or @MichaelXavier feel like it. What's the rush? You can add bab3565 to your `stack.yaml`.

**Comment by shmish111** [comment]
@bitemyapp I did not know you could do that, it's pretty cool.

**Comment by shmish111** [comment]
@bitemyapp using a git location is bloody hell, stack wants to recompile all the time for no apparent reason and bloodhound is slooooow at compiling. A release would be very much appreciated as it would make our lives so much more pleasant :-)

**Comment by bitemyapp** [comment]
@shmish111 mark it `extra-dep: true`

**Comment by shmish111** [comment]
@bitemyapp `extra-dep: true` doesn't always work, there are some situations where it rebuilds bloodhound and we can't work out when or why but it's fairly often in our development workflow, then we have to [https://xkcd.com/303/](https://xkcd.com/303/). It just so happens that bloodhound is a library that takes a long time to compile so it's bad luck on our part but a new release to hackage would solve that. Is there any reason not to?

**Comment by bitemyapp** [comment]
>`extra-dep: true` doesn't always work

Could you elaborate or provide an example? Sounds like something that should get filed as a bug on commercialhaskell/stack too.

**Comment by MichaelXavier** [comment]
I should have some time today to put together a changelog and cut a release.

**Comment by bitemyapp** [comment]
@MichaelXavier I'll get it, I want to take care of https://github.com/bitemyapp/bloodhound/issues/180 anyway.

**Comment by bitemyapp** [comment]
http://hackage.haskell.org/package/bloodhound 0.14.0.0 is up.

**Pull request merged**
