### PR TITLE
Add support for boosting fields in match query

### PR DESCRIPTION
**Pull request by thomasvnoort**

### CODE REVIEW

**Comment by bitemyapp** [comment]
@thomasvnoort did the tests pass locally for you? TravisCI has been very unreliable lately.

**Comment by thomasvnoort** [comment]
No they didn't. I get 3 failures, but these happen on master too so it seems to be unrelated.

**Comment by thomasvnoort** [comment]
I'm running ElasticSearch 1.6.0 by the way, that probably matters :)

**Comment by bitemyapp** [comment]
@thomasvnoort well, unrelated doesn't mean they don't need fixed. We can move ES version compat forward a notch if that's necessary but I am unlikely to do a non-trivial release without passing tests.

**Comment by thomasvnoort** [comment]
Sure, I agree tests need to succeed before releasing. I was just saying that I think it's unrelated to my changes and it probably requires you to look into it since it was failing before already. 

The three tests that fail for me on master and this PR (and my other PR), also fail on [Travis](https://travis-ci.org/bitemyapp/bloodhound/jobs/68304329#L715) for the earlier 1.4.1 version of ElasticSearch.

**Comment by thomasvnoort** [comment]
Any news on the broken tests?

**Comment by bitemyapp** [comment]
@thomasvnoort they're since fixed, I'll bounce the tests for this PR. If they're still broken in ~30 minutes, it's your code breaking them I think.

**Comment by bitemyapp** [comment]
@thomasvnoort appears to be your break.

**Comment by thomasvnoort** [comment]
This seems to be a different test failing than before, I'll have a look and fix it.

**Comment by thomasvnoort** [comment]
I resolved the conflicts and the tests are passing, this seems ready to be merged.

**Comment by bitemyapp** [comment]
@thomasvnoort merging the other broke this one, should be a quick merge I think.

**Comment by thomasvnoort** [comment]
It was indeed, all ready to be merged! Thanks!

**Comment by bitemyapp** [comment]
@thomasvnoort and we're in! Thank you again :dancer: :bear: :smile:

**Comment by thomasvnoort** [comment]
Great! Thanks!

**Pull request merged**
