### PR TITLE
add function for deleting alias

### PR DESCRIPTION
**Pull request by andrewthad**
resolves https://github.com/bitemyapp/bloodhound/issues/199

### CODE REVIEW

**Comment by bitemyapp** [comment]
Could I trouble you to add a test for this please?

**Comment by andrewthad** [comment]
I can get that added.

**Comment by bitemyapp** [comment]
Thank you!

**Comment by andrewthad** [comment]
The test for this is ready.

**Comment by bitemyapp** [comment]
Alright cool, thank you @andrewthad!

**Pull request merged**
