### PR TITLE
Sub aggs

### PR DESCRIPTION
**Pull request by bermanjosh**
For #164 and #163 

- Makes the sub-aggregation parser more generic to allow for named aggregations. Adds a test for this case. 
- Support basic clauses of the `top_hits` aggregation.

### CODE REVIEW

**Comment by bermanjosh** [comment]
Side question - is everyone ok with my changes to the stack.yaml? I'm on Windows, so symlinks are hit-and-miss. If not, feel free to switch it back, and I'll force my git to play nice.

**Comment by bitemyapp** [comment]
I can't really tell from the Github diff what changed other than the nightly bump and extra dep removal.

I'll assume that you changed a symlink into a real file that is duplicating other content.

I am hypothetically fine doing that but you need to deduplicate the content.

That means no more stack-8.0.yaml, just a default `stack.yaml` and an alternate version. Makefile/.travis.yml will need to be corrected too.

I'll let you decide whether this is more or less hassle than fixing symlinks on your system.

PR otherwise looks okay.

**Comment by bermanjosh** [comment]
> I'll assume that you changed a symlink into a real file that is duplicating other content.

Correct - I'll do the de-duplicating

**Comment by bermanjosh** [comment]
Done - I wasn't sure what you're using the Makefile for, so check my changes. I set GHC 8.0 as the default and added 7.10.

**Pull request merged**
