### PR TITLE
Fix docs specifying an incorrect terminating condition

### PR DESCRIPTION
**Pull request by MHova**
Addresses https://github.com/bitemyapp/bloodhound/issues/95

### CODE REVIEW

**Comment by MHova** [comment]
Err....what's up with the CI failure? @bitemyapp

**Comment by bitemyapp** [comment]
@MHova https://travis-ci.org/bitemyapp/bloodhound/jobs/105554260

beats the f out of me. 1.2.4 incompatibility?

**Comment by MHova** [comment]
So what should we do here? I've only changed comments and the README with this PR.

**Comment by bitemyapp** [comment]
@MHova check 1.2.4 docs, see if an API in-compat can be confirmed. Usually if it is, we just drop support for the oldest version and try to add a newer version in exchange, but I don't know that it'd be fair to ask you to do that.

**Comment by bitemyapp** [comment]
@MHova recycling this build to see what it does.

**Pull request merged**
