### PR TITLE
Master zoomin

### PR DESCRIPTION
**Pull request by renahkws**
Hi, we make heavy use of Elastic with Bloodhound at Zoominsoftware and we've been maintaining a fork for a while and adding features as we need them.
We recently merged your latest and greatest into our fork and now would like to submit our changes to be merged into the main for others to benefit from.
We've followed the Elastic docs pretty carefully, and are successfully using most of these changes in our prod environments.
Let us know what you think.
The updates include the following:
* Add support for MultiField QueryString queries - V1+V5
* Add MaxAggregation Type and supporting type: MissingValue - V5
* Add fields to TopHitsAggregation - V1+V5
* Add field collapse feature - V5
* Fix field collapse (types and exports)
* Add cardinality aggregation result type - V1+V5
* Add sort by script and supporting type: ScriptJ - V1+V5
* Add Unified Highlight - V5
* Fix typo so RequireFieldMatch actually works - V1+V5
* Add doc_as_upsert parameter to BulkUpdate - V1+V5
* Add delete scroll method + supporting types - V1+V5
* Fix Script object (and remove ScriptJ from V5)
* update tests

### CODE REVIEW

**Comment by bitemyapp** [comment]
Build's green on our end: https://travis-ci.org/bitemyapp/bloodhound/builds/397789694

But it looks like some of the test suites don't build or are failing with this PR. Before we spend time reviewing this large passel of changes, are you interested in fixing the build?

**Comment by renahkws** [comment]
Can you advise the best way to review the test suites? I tried running
stack test a number of times, and each time it just ate up most of the CPU
and disk for 20-30 minutes with no sign of finishing.

**Comment by bitemyapp** [comment]
>Can you advise the best way to review the test suites?

Pretty sure the `Makefile` has stuff in it. Failing that, you can see that the build failed in TravisCI. If you cannot get the test suite working locally you are welcome to spin this PR to keep tipping TravisCI over until you figure out why it's not working.

**Comment by bitemyapp** [comment]
@renahkws this PR changes too much and there's too much sustained brokenness for me to take the risk of merging this. I don't want to mislead you or misdirect your efforts so please don't do any further work on this for the sake of an upstream merge.

I'm closing this PR. If you'd like to get this into `master` then I would like to see individual, smaller changes justified and documented with passing tests that cover the new changes.

**Pull request closed without merging**
