### PR TITLE
Add Missing Aggregation support

### PR DESCRIPTION
**Pull request by MHova**
Addresses https://github.com/bitemyapp/bloodhound/issues/99

I would write a test for this, but I've been unable to get the tests to run locally.
1) `cabal install -j --only-dependencies --enable-tests` outputs this error:
```
src/Test/Hspec/Core/Type.hs:152:20:
    Constructor ‘HUnitFailure’ should have 2 arguments, but has been given 1
    In the pattern: HUnitFailure err
    In the first argument of ‘E.Handler’, namely
      ‘(\ (HUnitFailure err) -> return (Fail err))’
    In the expression:
      E.Handler (\ (HUnitFailure err) -> return (Fail err))
```

2) To fix the above error, I update the `hspec` bounds in `bloodhound.cabal` from `>= 1.8 && <2.2` to `>= 2.0 && <2.2`

3) Moving to hspec 2.0 causes this error:
```
tests/tests.hs:488:10:
    Duplicate instance declarations:
      instance (Arbitrary k, Ord k, Arbitrary v) => Arbitrary (M.Map k v)
        -- Defined at tests/tests.hs:488:10
      instance [overlap ok] [safe] (Ord k, Arbitrary k, Arbitrary v) =>
                                   Arbitrary (M.Map k v)
        -- Defined in ‘Test.QuickCheck.Arbitrary’
```
I fix it by removing that `Arbitrary` instance.

4) I reinstall and build. When I run `cabal tests` I get the message `You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.18.1.3, now Cabal-1.23.0.0).`

5) I run `cabal configure --enable-tests` and re-run `cabal tests`, but it doesn't make a difference.

Edit: Add bit about `Arbitrary`

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Have you tried stack? That's how our tests are run in CI.

**Comment by MHova** [comment]
Ah okay thanks. Got it working now after some fiddling. I'll make a test for this PR.

On a completely unrelated note, I'm going to enhance the README with instructions on how to run the tests...

**Comment by MHova** [comment]
@bitemyapp @MichaelXavier Test added and all tests passing. So I guess 1.2.4 does support this kind of aggregation after all?

**Comment by MichaelXavier** [comment]
Cool! Sounds like this is good to merge.

**Comment by bitemyapp** [comment]
@MHova @MichaelXavier thank you, collective of Michael. :busts_in_silhouette:

**Comment by MHova** [comment]
@bitemyapp Thanks! Also, resistance is futile.

Also also, when will this be released on Hackage? I need it for a work project.

**Comment by bitemyapp** [comment]
@MHova I can do a release soon. Most of the time is tracking down all the contributions and changes since last release and writing up the changelog.

**Comment by MHova** [comment]
Thanks for the quick response. I'd like to get this one in the release as well: https://github.com/bitemyapp/bloodhound/pull/89

This one is just a documentation change and is not critical to my project. Hopefully the recycled build will pass: https://github.com/bitemyapp/bloodhound/pull/96

**Comment by bitemyapp** [comment]
@MHova both in.

**Comment by bitemyapp** [comment]
@MHova another reason I was waiting on a release was to decide on a resolution of:  https://github.com/bitemyapp/bloodhound/issues/92

The existing users of the library already went through the pain of migrating to Aeson 0.10 (which probably broke some production code) and we're (I'm speaking for like, 2 people here) not keen to flip back.

Some sort of resolution to this problem is needed, probably requiring mutual Aeson 0.9 and 0.10 compatibility. Open to suggestions.

**Comment by MHova** [comment]
Okay I'll resort to a vendor fork in the meantime then.

**Comment by bitemyapp** [comment]
@MHova well, are you using Aeson 0.10? If so, then that's a vote for doing a release without bothering with LTS compat until things catch up.

**Comment by MHova** [comment]
Yes we are already using aeson 0.10 for our project.

**Comment by MHova** [comment]
Though I'm pretty sure we upgraded from aeson 0.9 to aeson 0.10 for the expressed purpose of using Bloodhound, so we can easily downgrade aeson if necessary.

**Comment by MichaelXavier** [comment]
Same. Bloodhound lead the charge into aeson 0.10 for us too.

**Comment by bitemyapp** [comment]
@MichaelXavier @MHova That's what I suspected. Given that, I am inapt to roll back.

**Pull request merged**
