### PR TITLE
Removed unnecessary conduit dependency

### PR DESCRIPTION
**Pull request by dmjio**

### CODE REVIEW

**Comment by bitemyapp** [comment]
Restarting build to make certain there isn't something spurious going on here.

**Comment by dmjio** [comment]
hrmmm, that's odd. Worked locally.

**Comment by bitemyapp** [comment]
@dmjio yeah I figured. Perhaps something with fixture installation on TravisCI?

**Comment by dmjio** [comment]
Yea, bet the sandboxes are cached on travis, the dep. removal probably caused cabal's SAT solver to produce a different set of deps. Wonder if the different deps. work, but cause different behavior. Maybe I'm overthinking. Let's just move to nix together? https://www.youtube.com/watch?v=BsBhi_r-OeE

Is there a way we can clear the cache in travis? CircleCI let's me do this.

**Comment by bitemyapp** [comment]
@dmjio re: cache - not really, I have to add a command in the script to nuke the sandbox and re-init.

I don't think it's your fault either, given:

https://travis-ci.org/bitemyapp/bloodhound/builds/65009159

I'm going to operate on that assumption, fix independently, rerun this build when it seems fixed, then merge. You're g2g on ignoring this PR unless I ping you, you've done your part. Thank you!

**Comment by dmjio** [comment]
cool! Thanks.

**Comment by bitemyapp** [comment]
>This pull request can be automatically merged.

Bloody finally.

**Pull request merged**
