### PR TITLE
Add updateDocument

### PR DESCRIPTION
**Pull request by dzhus**

### CODE REVIEW

**Comment by MichaelXavier** [comment]
This could use some tests :)

**Comment by dzhus** [comment]
I added tests.

**Comment by MichaelXavier** [comment]
@bitemyapp This looks good to me. One thing I'll note is that updates seem like they can also take a script with some additional parameters and configuration. I don't know anyone who uses this but if they did, we'd probably want to add an additional function to handle those updates.

**Comment by bitemyapp** [comment]
@MichaelXavier the scripting stuff is gnarly and I'm mostly hoping Haskellers generally are as keen as I am to avoid it.

**Comment by bitemyapp** [comment]
Thank you @dzhus ! :bear:

**Comment by dzhus** [comment]
Thank you for merging this

**Pull request merged**
