### PR TITLE
Support for 'Suggesters' and 'Template Queries'

### PR DESCRIPTION
**Pull request by bermanjosh**
This PR adds two functionalities:
* Inline 'template queries', which can be passed to the "_search" endpoint [1]
* A framework for 'suggesters' [2], with support for the 'Phrase Suggester' [3].
* It also includes a test which was requested in #172

A few notes:
* Tests for the new types and functions are included, along with some helper functions.
* Currently, this we're limiting to one suggestion request per search, although elastic supports 'n'.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-template-query.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters.htm
[3] https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-phrase.html

### CODE REVIEW

**Comment by bitemyapp** [comment]
@bermanjosh What about V5?

**Comment by bermanjosh** [comment]
@bitemyapp 
I believe everything is in both modules. I did the work in V5 and backported. Did you see something specific you think I missed?

**Comment by bermanjosh** [comment]
@bitemyapp Just checking on the status - thanks.

**Comment by bitemyapp** [comment]
@bermanjosh dunzokopf, sorry about the delay, was at LambdaConf. Let me know if you need anything else!

**Comment by bermanjosh** [comment]
@bitemyapp Thanks! There might be another PR over the next few weeks if I find I need more control over `generators` - I'm not sure yet.

**Pull request merged**
